# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""On-disk format contract for physicsnemo mesh zarr stores.

The store is generated by a session fixture (nothing committed to the repo);
format stability is enforced by asserting the exact on-disk *shape* of the
store -- group paths, attr names/values, array dtypes, chunking, and codecs.
A code change that alters the layout fails these assertions even though the
store regenerates, forcing format changes to be deliberate and versioned
(update the expectations here in the same PR that changes the format).
"""

import pytest
import zarr
from conftest import make_domain_mesh

from physicsnemo.mesh.io import to_zarr
from physicsnemo.mesh.io.io_zarr import _TYPE_ATTR


@pytest.fixture(scope="session")
def golden_store(tmp_path_factory):
    path = tmp_path_factory.mktemp("golden") / "domain_mesh.zarr"
    to_zarr(make_domain_mesh(), path, chunk_rows=16)
    return path


def test_root_contract(golden_store):
    root = zarr.open_group(str(golden_store), mode="r")
    assert root.attrs[_TYPE_ATTR] == "DomainMesh"
    # metadata is consolidated so opening costs one read
    assert root.metadata.consolidated_metadata is not None


def test_tree_contract(golden_store):
    root = zarr.open_group(str(golden_store), mode="r")
    groups = {name for name, _ in root.groups()}
    assert {"interior", "boundaries", "global_data"} <= groups
    boundaries = {name for name, _ in root["boundaries"].groups()}
    assert boundaries == {"wall", "inlet"}
    # a mesh group holds points (+ cells when present) and field subtrees
    wall = root["boundaries/wall"]
    arrays = {name for name, _ in wall.arrays()}
    assert {"points", "cells"} <= arrays
    assert "temp" in {name for name, _ in wall["point_data"].arrays()}
    # nested TensorDict fields serialize as nested groups
    assert "flow" in {name for name, _ in wall["point_data"].groups()}
    assert "velocity" in {name for name, _ in wall["point_data/flow"].arrays()}


def test_array_contract(golden_store):
    root = zarr.open_group(str(golden_store), mode="r")
    points = root["boundaries/wall/points"]
    assert str(points.dtype) == "float32"
    assert points.chunks[0] == 16  # chunk_rows reaches nested leaves
    codecs = [type(c).__name__ for c in points.metadata.codecs]
    assert "ZstdCodec" in codecs
    cells = root["boundaries/wall/cells"]
    assert str(cells.dtype) == "int64"
